# Generated by Django 2.1.4 on 2018-12-04 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='discord id'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='vip'),
        ),
        migrations.AddField(
            model_name='user',
            name='steam_id',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='steam id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='last login'),
            preserve_default=False,
        ),
    ]
